import test from 'node:test';
import http from 'node:http';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { unzipSync,strFromU8 } from 'fflate';
import { fixture,fakeRequest,generated,events } from './helpers.mjs';
const job=(r,mode='quick')=>({bookId:r.boot.books[0].id,pageId:r.store.book(r.boot.books[0].id).pages[0].id,mode,question:'Explain the failure modes.',selection:'durable queue'});

test('bootstrap exposes the exact model, never credentials; protected routes require the session token',async t=>{const r=await fixture(t,{key:'sk-test-not-real'});assert.equal(r.boot.model,'gpt-6-astra');assert.equal(r.boot.connected,true);assert.ok(!JSON.stringify(r.boot).includes('sk-test'));assert.equal((await fetch(`${r.url}/api/books`)).status,403);assert.equal((await r.call('/books','GET',undefined,{Origin:'https://untrusted.example'})).status,403);assert.equal(await new Promise((resolve,reject)=>{http.get(`${r.url}/api/bootstrap`,{headers:{Host:'untrusted.example'}},response=>{response.resume();resolve(response.statusCode);}).on('error',reject);}),403);assert.equal((await r.call('/books','GET',undefined,{'Sec-Fetch-Site':'cross-site'})).status,403);assert.equal((await r.call('/books')).status,200);});

test('import, edit, note, export, restore complete over HTTP',async t=>{const r=await fixture(t);const response=await r.call('/books','POST',{title:'Review',documents:[{title:'Plan',content:'# Plan\n\nA stable job key.',filename:'plan.md'}]});assert.equal(response.status,201);const book=await response.json(),p=book.pages[0];assert.equal((await r.call(`/books/${book.id}/pages/${p.id}`,'PATCH',{content:'# Plan\n\nRetry safely.'})).status,200);assert.equal((await r.call(`/books/${book.id}/pages/${p.id}/notes`,'POST',{text:'Ask about billing',status:'question'})).status,200);const zip=await r.call(`/books/${book.id}/export`);assert.equal(zip.headers.get('content-type'),'application/zip');const files=unzipSync(new Uint8Array(await zip.arrayBuffer()));const snapshot=JSON.parse(strFromU8(files['nested-book.json']));const restored=await (await r.call('/restore','POST',snapshot)).json();assert.equal(restored.pages[0].notes[0].text,'Ask about billing');assert.equal(restored.pages[0].revisions.length,1);assert.notEqual(restored.id,book.id);});

test('invalid imports and cyclic backups fail without creating a book',async t=>{const r=await fixture(t);const count=r.store.list().length;assert.equal((await r.call('/books','POST',{title:'',documents:[]})).status,400);const snapshot=structuredClone(r.store.db.books[0]);snapshot.pages[0].parentId=snapshot.pages[1].id;snapshot.pages[1].parentId=snapshot.pages[0].id;assert.ok((await r.call('/restore','POST',{version:1,book:snapshot})).status>=400);assert.equal(r.store.list().length,count);});

test('missing API key reports setup needed and never creates a fake answer',async t=>{const r=await fixture(t);const count=r.store.db.books[0].pages.length;const response=await r.call('/generate','POST',job(r));assert.equal(response.status,428);assert.match((await response.json()).error,/OpenAI API key/);assert.equal(r.store.db.books[0].pages.length,count);});

for(const mode of ['quick','page','deep','practice','feedback','brief'])test(`${mode} saves an anchored explanation with source evidence`,async t=>{const r=await fixture(t,{key:'fixture',request:fakeRequest});const input=job(r,mode);const out=await events(await r.call('/generate','POST',input));assert.equal(out.at(-1).type,'complete');const page=out.at(-1).pages[0];assert.equal(page.parentId,input.pageId);assert.equal(page.selection,'durable queue');assert.equal(page.model,'gpt-6-astra');assert.equal(page.sources[0].status,'matched');assert.equal(page.mode,mode);assert.ok(fs.existsSync(path.join(r.store.root,input.bookId,`${page.id}.md`)));});

test('research plans, reads chosen files, and writes two mutually linked Markdown children',async t=>{const calls=[];const r=await fixture(t,{key:'fixture',request:args=>{calls.push(args);return fakeRequest(args);}});const out=await events(await r.call('/generate','POST',job(r,'research')));assert.equal(calls.length,2);assert.equal(calls[0].name,'research_plan');assert.equal(calls[1].input.documents.length,3);const result=out.at(-1);assert.equal(result.type,'complete');assert.equal(result.pages.length,2);assert.match(result.pages[0].content,new RegExp(result.pages[1].id));assert.match(result.pages[1].content,new RegExp(result.pages[0].id));assert.equal(out.filter(x=>x.event?.kind==='read').length,3);assert.equal(out.at(-2).event.kind,'check');});

test('refine preserves the original page ID and a recoverable previous version',async t=>{const r=await fixture(t,{key:'fixture',request:fakeRequest}),input=job(r,'refine'),book=r.store.book(input.bookId),before=book.pages[0].content;const out=await events(await r.call('/generate','POST',input));assert.equal(out.at(-1).type,'complete');assert.equal(book.pages.length,3);assert.equal(book.pages[0].id,input.pageId);assert.equal(book.pages[0].revisions[0].content,before);assert.equal(book.pages[0].refinement.model,'gpt-6-astra');});

test('fabricated citations reject the entire response and persist no children',async t=>{const r=await fixture(t,{key:'fixture',request:async args=>{const out=await fakeRequest(args);if(args.name!=='research_plan')out.data.pages[0].sources[0].quote='This claim is not in the document.';return out;}});const out=await events(await r.call('/generate','POST',job(r,'research')));assert.equal(out.at(-1).type,'error');assert.match(out.at(-1).error,/citation did not match/);assert.equal(r.store.db.books[0].pages.length,3);});

test('concurrent changes reject stale generation instead of silently overwriting source',async t=>{let started,release;const entered=new Promise(resolve=>started=resolve),wait=new Promise(resolve=>release=resolve);const r=await fixture(t,{key:'fixture',request:async args=>{started();await wait;return fakeRequest(args);}});const input=job(r),pending=r.call('/generate','POST',input);await entered;await r.call(`/books/${input.bookId}/pages/${input.pageId}`,'PATCH',{content:'The source changed during the request.'});release();const out=await events(await pending);assert.equal(out.at(-1).type,'error');assert.match(out.at(-1).error,/source changed/);assert.equal(r.store.book(input.bookId).pages.length,3);});

test('cancel aborts the provider call and leaves no generated pages',async t=>{let started,aborted;const entered=new Promise(resolve=>started=resolve),canceled=new Promise(resolve=>aborted=resolve);const r=await fixture(t,{key:'fixture',request:({signal})=>new Promise((resolve,reject)=>{started();signal.addEventListener('abort',()=>{aborted();reject(new Error('aborted'));},{once:true});})});const controller=new AbortController();const response=await fetch(`${r.url}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json','X-Nested-Token':r.boot.token},body:JSON.stringify(job(r)),signal:controller.signal});await entered;controller.abort();await canceled;assert.equal(r.store.db.books[0].pages.length,3);await response.body.cancel().catch(()=>{});});

test('concurrent AI requests are rejected and the lock releases after failure',async t=>{let release,started;const wait=new Promise(resolve=>release=resolve),entered=new Promise(resolve=>started=resolve);const r=await fixture(t,{key:'fixture',request:async args=>{started();await wait;throw new Error('Provider unavailable');}});const pending=r.call('/generate','POST',job(r));await entered;assert.equal((await r.call('/generate','POST',job(r))).status,409);release();assert.equal((await events(await pending)).at(-1).type,'error');assert.equal((await r.call('/generate','POST',job(r))).status,200);});

test('unknown API routes and unavailable download return honest 404s rather than HTML success',async t=>{const r=await fixture(t);assert.equal((await r.call('/missing')).status,404);const download=await fetch(`${r.url}/downloads/Nested-arm64.zip`);assert.equal(download.status,404);assert.match(await download.text(),/not been packaged/);});

test('codex import refuses ChatGPT-only sessions without exposing secrets', async (t) => {
  const r = await fixture(t, { key: '' });
  const missing = await r.call('/settings/codex', 'POST');
  assert.equal(missing.status, 400);
  const body = await missing.json();
  assert.match(body.error || body.message || JSON.stringify(body), /API key|Codex|ChatGPT/i);
  assert.ok(!JSON.stringify(body).includes('sk-'));
});
