import './dom-setup.mjs';
import React from 'react';
import test from 'node:test';
import assert from 'node:assert/strict';
import {render,screen,fireEvent,waitFor,cleanup,act,within} from '@testing-library/react';
import Reader from '../src/Reader';
import {Marketing} from '../src/Marketing';
import {fixture,fakeRequest} from './helpers.mjs';
async function reader(t:any,connected=false){const r=await fixture(t,{key:connected?'fixture':'',request:fakeRequest});const realFetch=globalThis.fetch;t.mock.method(globalThis,'fetch',(url:any,options:any)=>realFetch(typeof url==='string'&&url.startsWith('/')?r.url+url:url,options));localStorage.clear();render(<Reader/>);t.after(cleanup);await screen.findByRole('heading',{name:'A plan for background jobs',level:1});return r;}

test('reader imports pasted Markdown, saves a note, edits, and restores a revision',async t=>{const r=await reader(t);fireEvent.click(screen.getByRole('button',{name:'New book',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Paste a document'}));fireEvent.change(screen.getByLabelText('Document title'),{target:{value:'My architecture'}});fireEvent.change(screen.getByLabelText('Markdown or plain text'),{target:{value:'# My architecture\n\nA unique token prevents duplicate work.'}});fireEvent.click(screen.getByRole('button',{name:'Start reading'}));await screen.findByRole('heading',{name:'My architecture'});fireEvent.click(screen.getByRole('tab',{name:'My notes'}));fireEvent.change(screen.getByLabelText('Your note'),{target:{value:'Check the billing boundary.'}});fireEvent.click(screen.getByRole('button',{name:'Save note'}));await screen.findByText('Check the billing boundary.');fireEvent.click(screen.getByRole('button',{name:'Edit page',exact:true}));fireEvent.change(screen.getByLabelText('Markdown'),{target:{value:'# My architecture\n\nA changed design.'}});fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await screen.findByText('A changed design.');fireEvent.click(screen.getByRole('button',{name:'Page history',exact:true}));await screen.findByRole('heading',{name:'How this page changed.'});fireEvent.click(screen.getByRole('button',{name:'Restore this version'}));await screen.findByText('A unique token prevents duplicate work.');const book=r.store.db.books.find((b:any)=>b.title==='My architecture');assert.equal(book.pages[0].notes.length,1);assert.equal(book.pages[0].revisions.length,2);});

test('selection anchors a quick answer; research grows the navigable book map',async t=>{const r=await reader(t,true);const text=screen.getByTestId('document-content').querySelector('p')!;const range=document.createRange();range.selectNodeContents(text);act(()=>{window.getSelection()!.removeAllRanges();window.getSelection()!.addRange(range);document.dispatchEvent(new Event('selectionchange'));});await screen.findByText('From your selection');fireEvent.change(screen.getByRole('textbox',{name:'Your question'}),{target:{value:'Explain the failure mode.'}});fireEvent.click(screen.getByRole('button',{name:'Ask',exact:true}));await screen.findByRole('heading',{name:'Explanation 1'});assert.ok(r.store.db.books[0].pages.at(-1).selection.length>10);fireEvent.click(screen.getByRole('button',{name:'Open this explanation'}));await screen.findByRole('heading',{name:'Explanation 1',level:1});fireEvent.change(screen.getByRole('combobox',{name:'Explanation mode'}),{target:{value:'research'}});fireEvent.change(screen.getByRole('textbox',{name:'Your question'}),{target:{value:'Investigate the tradeoff.'}});fireEvent.click(screen.getByRole('button',{name:'Ask',exact:true}));await waitFor(()=>assert.equal(r.store.db.books[0].pages.length,6));await screen.findByText('2 research pages added to your book.');fireEvent.click(screen.getByRole('button',{name:'Book map',exact:true}));await screen.findByRole('heading',{name:'Your book, unfolding.'});assert.ok(screen.getAllByText('Research chapter').length>=2);});

test('missing-key action opens setup without producing a pretend answer',async t=>{const r=await reader(t);fireEvent.click(screen.getByRole('button',{name:'Connect to ask'}));await screen.findByRole('heading',{name:'Connect GPT-6 Astra'});assert.equal(r.store.db.books[0].pages.length,3);assert.ok(screen.getByText('gpt-6-astra'));});

test('search locates content and opens the matched source',async t=>{await reader(t);fireEvent.change(screen.getByRole('textbox',{name:'Search this book'}),{target:{value:'heartbeat'}});const result=await screen.findByRole('button',{name:/Failure cases worth testing/});fireEvent.click(result);await screen.findByRole('heading',{name:'Failure cases worth testing',level:1});});

test('marketing examples switch, FAQs expand, and calls to action point to real routes',async t=>{render(<Marketing/>);t.after(cleanup);assert.ok(screen.getByRole('heading',{name:/Finally understand/}));fireEvent.click(screen.getByRole('button',{name:/Do we need a separate queue/}));assert.ok(screen.getByText(/A separate broker introduces another service/));assert.equal(screen.getByRole('link',{name:'Find your first question'}).getAttribute('href'),'/app');assert.equal(screen.getByRole('link',{name:'Download for Mac'}).getAttribute('href'),'/downloads/Nested-arm64.zip');fireEvent.click(screen.getByRole('button',{name:'Privacy'}));assert.ok(screen.getByText(/This preview uses no analytics/));});
