import {useEffect,useRef,useState} from 'react';
import {X,Upload,FileText,FolderOpen,ArrowUpRight} from 'lucide-react';
import type {DocumentInput} from '../types';
import {unzipSync,strFromU8} from 'fflate';
export function Importer({onClose,onImport,onRestore}:{onClose:()=>void;onImport:(docs:DocumentInput[],name:string)=>Promise<void>;onRestore:(data:unknown)=>Promise<void>}){
 const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{dialogRef.current?.showModal();return()=>dialogRef.current?.close();},[]);
 const [tab,setTab]=useState<'files'|'paste'>('files'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[name,setName]=useState(''),[docs,setDocs]=useState<DocumentInput[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const fileRef=useRef<HTMLInputElement>(null),folderRef=useRef<HTMLInputElement>(null);
 async function load(files:FileList|File[]|null){if(!files)return;setError('');try{const all=Array.from(files);if(all.length===1&&all[0].name.endsWith('.zip')){if(all[0].size>12_000_000)throw new Error('Backups must be smaller than 12 MB.');const zip=unzipSync(new Uint8Array(await all[0].arrayBuffer()),{filter:file=>file.name==='nested-book.json'&&file.originalSize<12_000_000});if(!zip['nested-book.json'])throw new Error('This ZIP is not a Nested book export.');setBusy(true);await onRestore(JSON.parse(strFromU8(zip['nested-book.json'])));onClose();return;}
 const accepted=all.filter(f=>/\.(md|markdown|txt)$/i.test(f.name));if(!accepted.length)throw new Error('Choose Markdown or text files, or a Nested ZIP backup.');if(accepted.length>100)throw new Error('Import up to 100 files at a time.');if(accepted.some(f=>f.size>500000))throw new Error('Each file must be smaller than 500 KB.');const loaded=await Promise.all(accepted.map(async f=>{const content=await f.text();return {title:content.match(/^# (.+)/m)?.[1]||f.name.replace(/\.[^.]+$/,''),content,filename:f.webkitRelativePath||f.name};}));if(loaded.some(d=>!d.content.trim()))throw new Error('One of these files is empty. Remove it and try again.');setDocs(loaded);setName(accepted[0].webkitRelativePath?.split('/')[0]||loaded[0].title);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(){setBusy(true);setError('');try{await onImport(tab==='paste'?[{title:title.trim()||'Untitled document',content:body}]:docs,name.trim()||title.trim()||'Untitled book');onClose();}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="modal-backdrop"><dialog ref={dialogRef} className="import-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="import-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();}}><div className="dialog-heading"><div><span className="eyebrow">A new starting point</span><h2 id="import-title">Bring something to understand.</h2></div><button className="icon-button" aria-label="Close import" onClick={onClose} disabled={busy}><X size={20}/></button></div><p className="muted">An agent’s plan, a research brief, or that document you’ve been meaning to read.</p><div className="segmented"><button className={tab==='files'?'active':''} onClick={()=>setTab('files')}>Open files</button><button className={tab==='paste'?'active':''} onClick={()=>setTab('paste')}>Paste a document</button></div>{tab==='files'?<><div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void load(e.dataTransfer.files);}}><Upload size={30}/><h3>Drop your Markdown here</h3><p>.md, .txt, a folder, or a Nested book .zip</p><div className="button-row"><button className="button primary" onClick={()=>fileRef.current?.click()}><FileText size={16}/>Choose files</button><button className="button" onClick={()=>folderRef.current?.click()}><FolderOpen size={16}/>Choose folder</button></div><input ref={fileRef} type="file" multiple accept=".md,.markdown,.txt,.zip" hidden onChange={e=>void load(e.target.files)}/><input ref={folderRef} type="file" multiple hidden {...{webkitdirectory:''} as any} onChange={e=>void load(e.target.files)}/></div>{docs.length>0&&<><label className="field-label">Book title<input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><ul className="file-list">{docs.map((d,i)=><li key={i}><FileText size={14}/>{d.title}</li>)}</ul></>}</>:<><label className="field-label">Document title<input autoFocus placeholder="For example, Our next architecture" value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label className="field-label">Markdown or plain text<textarea rows={10} placeholder="# The plan…" value={body} maxLength={500000} onChange={e=>setBody(e.target.value)}/></label></>}{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-footer"><span className="muted small-text">Saved as local Markdown. Yours to keep.</span><button className="button primary" disabled={busy||(tab==='paste'?!body.trim():!docs.length)} onClick={()=>void submit()}>{busy?'Opening…':'Start reading'}<ArrowUpRight size={17}/></button></div></dialog></div>
}
